### PR TITLE
Fixed ItemsViewModel removeAt position less than 0 crash.

### PR DESCRIPTION
**Pull request by Richyeohx**

### CODE REVIEW

**Comment by Richyeoh** [comment]
What？

**Comment by Richyeohx** [comment]
I signed it!

**Comment by gielzak** [comment]
Hi, apologies, we were focusing on other stuff and missed this. Happy to take your pull request. We've had to refactor package names, so there is a conflict now.

Let me know if you prefer to resolve here, or I if you prefer I take your code and apply myself manually.

**Comment by Richyeohx** [comment]
> Hi, apologies, we were focusing on other stuff and missed this. Happy to take your pull request. We've had to refactor package names, so there is a conflict now.
> 
> Let me know if you prefer to resolve here, or I if you prefer I take your code and apply myself manually.

Is such that. I think it's better to add a less than zero detection in the ViewModel so that no array out of bounds exception are generated.

**Comment by codingjeremy** [comment]
Looks like this PR still has conflicts to resolve. We actually migrated [this sample to a new location](https://github.com/android/views-widgets-samples).

I'm closing this one since the new repo is a bit different. Please recreate in the new location and we can definitely accept. Thank you!

**Pull request closed without merging**
